plugins {
    id "net.fabricmc.fabric-loom" version "${loom_version}"
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    mavenCentral()
    maven {
        name = "MaxHenkel"
        url = "https://maven.maxhenkel.de/repository/public"
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    implementation "de.maxhenkel.voicechat:voicechat-api:${project.voicechat_api_version}"
    runtimeOnly "maven.modrinth:simple-voice-chat:fabric-${project.voicechat_version}"
    runtimeOnly "de.maxhenkel.voicechat:voicechat-api:${project.voicechat_api_version}:fabric-stub"

    include implementation("com.googlecode.soundlibs:mp3spi:1.9.5.4")
    include implementation("com.googlecode.soundlibs:vorbisspi:1.0.3.3")
    include implementation("com.googlecode.soundlibs:tritonus-share:0.3.7.4")

    testImplementation platform("org.junit:junit-bom:6.0.0")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "voicechat_api_version": project.voicechat_api_version
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = "UTF-8"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withSourcesJar()
}

test {
    useJUnitPlatform()
}
