org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.17-SNAPSHOT
fabric_api_version=0.155.2+26.1.2
voicechat_version=2.6.21+26.1.2
voicechat_api_version=2.6.0

mod_version=1.0.0
maven_group=de.minecraftmodmaker
archives_base_name=choicer-voicer
